version: 2

registries:
  ecr:
    type: docker-registry
    url: https://127178877223.dkr.ecr.us-east-2.amazonaws.com
    username: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
    password: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github_actions

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ruby
