version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    reviewers:
      - get-bridge/oberbaum

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    reviewers:
      - get-bridge/oberbaum

  # These are not meant to be automatically accepted
  # because they're templated files, however this will
  # give us a way to be automatically notified when there
  # are upstream changes to roll into our own templates.
  - package-ecosystem: docker
    directory: core/jammy
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: core/jammy-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: core/bionic
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: core/bionic-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/8
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/8-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/10
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/10-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/12
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/12-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/14
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/14-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/16
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/16-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/18
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/18-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/19
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: node/19-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: ruby/2.7
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: ruby/2.7-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: ruby/3.0
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: ruby/3.0-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: ruby/3.1
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender

  - package-ecosystem: docker
    directory: ruby/3.1-fat
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - notification-only
    assignees:
      - djbender
