require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  DefaultFormatter: progress
  DisplayCopNames: true
  TargetRubyVersion: 3.2

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
