plugins:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  DefaultFormatter: progress
  DisplayCopNames: true
  TargetRubyVersion: 3.2

Metrics/AbcSize:
  Enabled: true
  AllowedMethods: [ ]
  AllowedPatterns: [ ]
  CountRepeatedAttributes: true
  Max: 60

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 40
  CountAsOne: [ ]
  AllowedMethods: [ ]
  AllowedPatterns: [ ]

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
