name: Publish TechDocs

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/techdocs.yaml"
      - "docs/**"
      - "mkdocs.yml"

jobs:
  publish-techdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          repository: get-bridge/developer_portal
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/developer_portal
          ref: master
      - uses: ./.github/developer_portal/.github/actions/techdocs
        with:
          entity_name: "DockerBaseImages"
          entity_kind: "Component"
          entity_namespace: "default"
